server:
  port: 8090

spring:
  application:
    name: jdbc
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://localhost:5432/gistdb1
    user: postgres
    password: postgres

  datasource:
    url: ${spring.liquibase.url}
    username: ${spring.liquibase.user}
    password: ${spring.liquibase.password}

logging:
  level:
    org.springframework.web: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
